//AngularUI router
define([
    'require',
    'angular',
    'app'
],function(require,angular,app){
    return app.config(['$stateProvider','$urlRouterProvider',function ($stateProvider,$urlRouterProvider) {
        $stateProvider
            .state('rootState.AngularUIstate',{
                url:'/angularUI',
                views:{
                    'ContentView':{
                        templateUrl:'tpls/AngularUI/AngularUImain.html',
                    },
                    'ContentView.angularUiSideNav':{
                        templateUrl:'tpls/AngularUI/AngularUiSideNavBar.html'
                    },
                    'ContentView.angularUiContent':{
                        templateUrl:'tpls/AngularUI/AngularUI-pagination.html'
                    }
                }
            })
            .state('rootState.AngularUIstate.paginationState',{
                url:'/pagination',
                views:{
                    'angularUiContent':{
                        templateUrl:'tpls/AngularUI/AngularUI-pagination.html',
                        //controller:'angularUiPaginationController'
                    }
                }
            })
            .state('rootState.AngularUIstate.directiveShareState',{
                url:'/directiveShare',
                views:{
                    'angularUiContent':{
                        templateUrl:'tpls/AngularUI/directiveControllerShare.html',
                        //controller:'directiveShareController'
                    }
                }
            })
            .state('rootState.AngularUIstate.otherState',{
                url:'/other',
                views:{
                    'angularUiContent':{
                        templateUrl:'tpls/AngularUI/AngularUIother.html'
                    }
                }
            })
            .state('rootState.AngularUIstate.accordionState',{
                url:'/accordion',
                views:{
                    'angularUiContent':{
                        templateUrl:'tpls/AngularUI/accordion.html',
                        //controller:'accordionController'
                    }
                }
            })
            .state('rootState.AngularUIstate.directiveScopeState',{
                url:'/directiveScope',
                views:{
                    'angularUiContent':{
                        templateUrl:'tpls/AngularUI/directiveScope.html',
                        //controller:'directiveScopeController'
                    }
                }
            })
            .state('rootState.AngularUIstate.formSubmitState',{
                url:'/formSubmit',
                views:{
                    'angularUiContent':{
                        templateUrl:'tpls/AngularUI/formSubmit.html',
                        controller:'formSubmitController'
                    }
                }
            })
    }]);
})