define([
    "angular",
    "require",
    "angular-ui-router",
    "jquery",
    "app",
    "rootRouter",
    "rootControllers",
    "rootDirective",
    "ui-bootstrap",
    "ui-bootstrap-tpls",
    "angular-animate",
    'rootService',
    'rootFilter'
],function(uiRouter,$,app,router,rootCtrl,rootDirective){
    require(['domReady!'],function (document) {
        angular.bootstrap(document,['myApp','ngAnimate']);
    })
});
